---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: "{{ cloud | default('openstack') }}"
    register: result

  - name: debug
    debug:
      var: "{{result.openstack_servers}}"

  - name: Delete instances
    os_server:
      cloud: "{{ cloud | default('openstack') }}"
      delete_fip: True
      name: "{{ item.name }}"
      state: absent
    with_items: "{{result.openstack_servers}}"
   
