---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: "{{ cloud | default('openstack') }}"
    register: instance_info

  - name: debug
    debug:
      var: instance_info.openstack_servers

  - name: Delete instances
    os_server:
      cloud: "{{ item.cloud | default('openstack') }}"
      delete_fip: True
      name: "{{ item.id }}"
      state: absent
    loop: 
      - "{{ instance_info.openstack_servers }}"
   
