---
- name: install {{ payload }}
  package:
    name: "{{payload}}"
    state: present

- name: configure software
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart {{payload}}