---
- name: install {{ payload }}
  package:
    name: "{{payload}}"
    state: present

- name: start and ensure is enabled service {{ payload }}
  service: 
    name: "{{payload}}"
    enabled: yes
    state: started

- name: configure software
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart {{payload}}