---
- name: install package
  package:
    name: haproxy
    state: present

- name: configure software
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: haproxy_started