---
# tasks file for osp.servers
- name: Create instances
  os_server:
    cloud: "{{ item.cloud | default('openstack') }}"
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.ansible_key | default(omit) }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.secgroup | default(omit) }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ item.priv_net }}"
    meta: "{{ item.meta | default (omit) }}"
    userdata: "{{ item.userdata | default(omit) }}"
  loop: "{{ instances }}"

- name: Add/Remove floating IP from an instance
  os_floating_ip:
    cloud: "{{ item.cloud | default('openstack') }}"
    server: "{{ item.name }}"
    network: "{{ item.pub_net }}"
  loop: "{{ instances }}"
