---
- name: install {{ payload }}
  package:
    name: "{{item}}"
    state: present
  loop:
    - java-1.8.0-openjdk
    - "{{payload}}"
  
- name: verify folder exist for {{ payload }}
  file:
    state: directory
    path: "{{tomcat_web_root}}"

- name: start and ensure is enabled service {{ payload }}
  service: 
    name: "{{payload}}"
    enabled: yes
    state: started
    
- name: configure {{ payload }}
  template:
    src: index.html.j2
    dest: "{{tomcat_web_root}}/index.html"  
  notify: start {{ payload }}
